config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  resources :posts, only: [:index, :show]
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :admin do
    get '/', to: 'users#index'
    post 'groups/add_member'
    delete 'groups/destroy_member'

    resources :groups
    resources :posts
    resources :users
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, Post, id: Post.current_posts(user).ids
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users 
  has_many :memberships, as: :memberable
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :memberable, polymorphic: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_one :membership 
  has_one_attached :file 

  validates :description, :title, presence: true

  def recipients_emails
    if  self.membership.memberable_type == 'User'
      self.membership.memberable.email
    else
      self.membership.memberable.users.pluck(:email)
    end
  end

  def self.current_posts(user)
    mem_ids = (Membership.where(memberable_type: "User", memberable_id: user.id).ids << Membership.where(memberable_type: 'Group', memberable_id: user.groups.ids).ids).flatten
    Post.joins(:membership).where(memberships: {id: mem_ids})
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_and_belongs_to_many :groups
  has_many :memberships, as: :memberable

  enum role: [:user, :admin]

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def admin?
    self.role == 'admin'
  end

  def self.not_group_members(group_id)
    User.where.not(id: Group.find(group_id).users.ids)
  end

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ActionController::Base
  
  before_action :admin?

  layout 'admin'
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  private 

  def admin?
    redirect_to root_path, alert: 'You do not have permissions' unless current_user.admin?
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::AdminsController
  
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_member, :destroy_member]
  
  def new
    @group = Group.new
  end

  def index
    @count  = 0
    @groups = Group.all
  end

  def show
    @count = 0
    @users = @group.users
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = 'Successfully created'
    else
      render :new
    end
    redirect_to admin_group_path(@group.id)
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      flash[:notice] = 'Successfully updated'
    else
      render edit
    end
    redirect_to admin_group_path(@group.id)
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Successfully deleted'
    else
      flash[:notice] = 'Not deleted'
    end
    redirect_to admin__path 
  end

  def add_member
    @group.users << User.find(params[:user_id])
    redirect_to admin_group_path(@group.id)
  end

  def destroy_member
    @group.users.delete(User.find(params[:user_id]))
    flash[:notice] = 'Successfully deleted'
    redirect_to admin_group_path(@group.id) 
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/admin/posts_controller.rb
  class Admin::PostsController < Admin::AdminsController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def index
    @count = 0 
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if shared?
      @post.membership = Membership.new(memberable_type: params[:share_for], memberable_id: memberable_id) 
    end

    if @post.save!
      PostMailer.post_created(@post.recipients_emails, @post).deliver_now if shared?
      redirect_to admin_post_path(@post)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to admin_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.delete
      flash[:notice] = 'Successfully deleted'
    else
      flash[:notice] = 'Not deleted'
    end
    redirect_to admin_posts_path 
  end

  private

  def shared?
    params[:share_for] != 'None'
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :file)
  end

  def memberable_id
    params[:share_for] == "User" ? params[:user] : params[:group]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @count = 0
  end

  def show
  end

  def edit  
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.delete
      flash[:notice] = 'Successfully deleted'
    else
      flash[:notice] = 'Not deleted'
    end
    redirect_to admin_users_path 
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def authenticate_user!
    redirect_to new_user_session_path , alert: 'Not authorized.' if !signed_in?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index 
    @posts = Post.current_posts(current_user)
    @count = 0
    render 'admin/posts/index'
  end

  def show
    @post = Post.find(params[:id])
    render 'admin/posts/show'
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/groups/_add_member.html.slim
#myModal.modal.fade.p-4 role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-head.m-2.h4 Add new member
      .modal-body
        = form_tag(admin_groups_add_member_path, method: :post)
          = select_tag 'user_id', options_from_collection_for_select(User.not_group_members(@group.id), "id", "full_name")
          = hidden_field_tag 'id', @group.id 
          = submit_tag "Add new member", class: 'btn btn-success'

app/views/admin/groups/_group_form.html.slim
= simple_form_for [:admin, @group] do |f|
  = f.input :name 
  = f.submit 'Submit', class: 'btn btn-success'

app/views/admin/groups/edit.html.slim
.container
  .row
    .col-12
      = render 'admin/groups/group_form'

app/views/admin/groups/index.html.slim
.container
  .row
    .col-12
      = link_to 'New Group', new_admin_group_path, class: 'btn btn-success mt-3'
      .col-12.mt-3
      table.table.table-striped.table-bordered.table-dark
        thead
          tr
            th scope="col"  #
            th scope="col"  Group name
            th scope="col"  Actions
        tbody
          - @groups.each do |group|
            tr
              th scope="row" 
                = @count += 1
                td= group.name
                td 
                  = link_to 'Show', admin_group_path(group.id), class: 'btn btn-primary mx-1'
                  = link_to 'Edit', edit_admin_group_path(group.id), class: 'btn btn-warning mx-1'
                  = link_to 'Delete', admin_group_path(group.id), method: :delete, class: 'btn btn-danger mx-1'

app/views/admin/groups/new.html.slim
.container
  .row
    .col-12
      = render 'admin/groups/group_form'

app/views/admin/groups/show.html.slim
.container
  .row
    .col-12.my-3
      button.btn.btn-success data-target="#myModal" data-toggle="modal" type="button"  Add new member
      .h2 Name 
      .h5 = @group.name
      .h2 Members
      table.table.table-striped.table-bordered.table-dark
        thead
          tr
            th scope="col"  #
            th scope="col"  Full name
            th scope="col"  Email
            th scope="col"  Actions
        tbody
          - @users.each do |user|
            tr
              th scope="row" 
                = @count += 1
                td
                  = user.full_name
                td
                  = user.email
                td 
                  = link_to 'Show', admin_user_path(user.id), class: 'btn btn-primary mx-1'
                  = link_to 'Delete from group', admin_groups_destroy_member_path(user_id: user.id, id: @group.id), method: :delete, class: 'btn btn-danger mx-1'
      = render partial: 'admin/groups/add_member'

app/views/admin/posts/_posts_form.html.slim
= simple_form_for([:admin, @post], html: { class: 'form-group' }) do |f|
  = f.input :title, placeholder: 'title'
  = f.input :description, placeholder: 'description'
  = f.input :file, as: :file 
  .col-12
    = radio_button_tag 'share_for', 'User', class: 'form-check-input'
    | Share for user
    = select_tag 'user', options_from_collection_for_select(User.all, 'id', 'full_name')
  .col-12
    = radio_button_tag 'share_for', 'Group'
    | Share for group
    = select_tag 'group', options_from_collection_for_select(Group.all, 'id', 'name')
  .col-12
    = radio_button_tag 'share_for', 'None'
    | Don't share post

  = f.button :submit, class: 'btn btn-success'

app/views/admin/posts/edit.html.slim
.container.mt-5
  .row
    .col-4
      = render partial: 'admin/posts/posts_form'

app/views/admin/posts/index.html.slim
.container
  .row
    .col-12.mt-5
      - if can? :craete, @post
        = link_to 'Create new post', new_admin_post_path, class: 'btn btn-success my-2'
      table.table.table-striped.table-bordered.table-dark
        thead
          tr
            th scope="col"  #
            th scope="col"  Title
            th scope="col"  Created at
            th scope="col"  Actions
        tbody
          - @posts.each do |post|
            tr
              th scope="row" 
                = @count += 1
                td= post.title
                td= post.created_at
                td
                  - if can? :read, @post 
                    = link_to 'Show', admin_post_path(post.id), class: 'btn btn-primary mx-1'
                  - if can? :update, @post
                    = link_to 'Edit', edit_admin_post_path(post.id), class: 'btn btn-success mx-1'
                  - if can? :destroy, @post
                    = link_to 'Delete', admin_post_path(post.id), method: :delete, class: 'btn btn-danger mx-1'

app/views/admin/posts/new.html.slim
.container.mt-5
  .row
    .col-4
      = render partial: 'admin/posts/posts_form'

app/views/admin/posts/show.html.slim
.container
  .row
    .col-12
      table.table.table-striped.table-bordered.table-dark.mt-5
        thead
          tr
            th scope="col"  Title
            th scope="col"  Description
            - if @post.file.attached?
              th scope="col"  File
            th scope="col"  Created at
        tbody
            tr
              td= @post.title
              td= @post.description
              - if @post.file.attached?
                td= link_to 'download_file', url_for(@post.file), target: 'balnk'
              td= @post.created_at
      = link_to 'All posts', admin_posts_path, class: 'btn btn-success'

app/views/admin/users/edit.html.slim
.container
  .row
    .col-4
      = simple_form_for([:admin, @user], html: { class: 'form-group' }) do |f|
        = f.input :first_name, placeholder: 'first name'
        = f.input :last_name, placeholder: 'last name'
        = f.input :email, placeholder: 'user@domain.com'
        = f.button :submit, class: 'btn btn-success'

app/views/admin/users/index.html.slim
.container
  .row
    .col-12.mt-5
      table.table.table-striped.table-bordered.table-dark
        thead
          tr
            th scope="col"  #
            th scope="col"  Full name
            th scope="col"  Email
            th scope="col"  Actions
        tbody
          - @users.each do |user|
            tr
              th scope="row" 
                = @count += 1
                td
                  = user.full_name
                td
                  = user.email
                td 
                  = link_to 'Show', admin_user_path(user.id), class: 'btn btn-primary mx-1'
                  = link_to 'Edit', edit_admin_user_path(user.id), class: 'btn btn-success mx-1'
                  = link_to 'Delete', admin_user_path(user.id), method: :delete, class: 'btn btn-danger mx-1'

app/views/admin/users/show.html.slim
.container
  .row
    .col-12
      table.table.table-striped.table-bordered.table-dark
        thead
          tr
            th scope="col"  Full name
            th scope="col"  Email
        tbody
            tr
              td
                = @user.full_name
              td
                = @user.email

app/views/layouts/_admin_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'HR-Department', root_path, class: 'navbar-brand'
  = link_to 'Posts', admin_posts_path,  class: 'nav-link'
  = link_to 'Users', admin_users_path,  class: 'nav-link'
  = link_to 'Groups', admin_groups_path,class: 'nav-link'
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  - if user_signed_in?
    li.text-left
      = link_to('Logout', destroy_user_session_path, method: :delete)
  - else
    li.text-right
      = link_to('Login', new_user_session_path)

app/views/layouts/_alerts.html.slim
- if notice
  p.notice.alert.alert-info
    = notice
    button.close aria-label="Close" data-dismiss="alert" type="button" 
      span aria-hidden="true"  ×
- if alert
  p.alert.alert-info
    = alert
    button.close aria-label="Close" data-dismiss="alert" type="button" 
      span aria-hidden="true"  ×

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'HR-Department', root_path, class: 'navbar-brand'
  = link_to 'My account', edit_user_registration_path, class: 'navbar'
  - if current_user && current_user.admin?
    = link_to 'Admin', admin_users_path, class: 'navbar'
  = link_to 'Shared posts', posts_path, class: 'navbar'
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  - if user_signed_in?
    li.text-left
      = link_to('Logout', destroy_user_session_path, method: :delete)
  - else
    li.text-right
      = link_to('Login', new_user_session_path)

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrDepartment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/admin_navbar' %>
    <%= render partial: 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrDepartment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>